# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ef008af066f5e0ab6eb8dfce09873188eeda1f7f019f1c2064f6079f99530ebeb97198f250325cba4aa1b6aa273eeb284ed3f3d5ac6c88b5c19dfee674b2cf88

test:
  secret_key_base: 5090493cb21c5fe7dc7a1347d461a91fb3e04a222469834ad47ec1b46cf8db8389164db3f438d11cffb9d470e022e613b3318042d56eaa80f510437e51fc7e53

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
